<a href="https://colab.research.google.com/github/mohumedraslan/Operations-on-Tensor/blob/main/Operations_On_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)


2.18.0


In [2]:
first_const = tf.constant([[1,2],[3,4]], dtype=tf.float32)

print(first_const)
print(first_const.numpy())
print(first_const.shape)
print(first_const.device)
print(first_const.dtype)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
[[1. 2.]
 [3. 4.]]
(2, 2)
/job:localhost/replica:0/task:0/device:CPU:0
<dtype: 'float32'>


In [3]:
zeros_like_c = tf.zeros_like(first_const) # View generated data.
zeros_like_c.numpy()

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [4]:
filled_tensor = tf.fill([3,4],7)
print(filled_tensor)

tf.Tensor(
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]], shape=(3, 4), dtype=int32)


In [5]:
random_const =tf.random.normal([5,5],mean=0.5,stddev=1,dtype=tf.float32)
random_const


<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 0.9759669 , -1.4985414 ,  0.2442458 , -2.520329  ,  0.65542066],
       [-0.39594632,  0.8260763 ,  0.26375186,  1.2311223 ,  0.0173575 ],
       [-2.1159368 , -0.37704504,  0.18794984,  0.5277171 ,  3.6716967 ],
       [ 0.3612119 ,  1.1320012 , -1.5874805 ,  0.776104  , -1.0226879 ],
       [-0.18579209,  1.0840354 ,  1.1024119 , -0.07119125,  0.19031   ]],
      dtype=float32)>

In [6]:
list_1 = [1,2,3,4,5,6]
list_t = tf.convert_to_tensor(list_1,dtype=tf.float32)
list_t

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float32)>

In [7]:
var_1 = tf.Variable(tf.ones([2,3]))
var_1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [8]:
print("Value of var_1:", var_1.numpy())

# Assign a new value to the variable
var_value_1 = [[1, 2, 3], [4, 5, 6]]
var_1.assign(var_value_1)

# Print the new value
print("New value for var_1:", var_1.numpy())

Value of var_1: [[1. 1. 1.]
 [1. 1. 1.]]
New value for var_1: [[1. 2. 3.]
 [4. 5. 6.]]


In [9]:
var_1.assign_add(tf.ones([2,3]))
var_1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[2., 3., 4.],
       [5., 6., 7.]], dtype=float32)>

In [10]:
# Create a 4D tensor representing 4 images of size 100x100 with 3 color channels
tensor_h = tf.random.normal([4, 100, 100, 3])

# Extract the first image
first_image = tensor_h[0, :, :, :]
print("First image shape:", first_image.shape)

# Extract every second image
every_second_image = tensor_h[::2, ...]
print("Every second image shape:", every_second_image.shape)

# Slice data from the last element
last_element_slice = tensor_h[:-1]
print("Last element slice shape:", last_element_slice.shape)

# Indexing: Get the pixel at position [20, 40] in the second channel of the first image
pixel_value = tensor_h[0][19][39][1]
print("Pixel value at [20, 40] in the second channel of the first image:", pixel_value)

# Extract specific images using tf.gather
indices = [0, 1, 3]
gathered_images = tf.gather(tensor_h, indices=indices, axis=0)
print("Gathered images shape:", gathered_images.shape)
print(gathered_images)
# Extract specific pixels using tf.gather_nd
indices_nd = [[0, 1, 1, 0], [1, 2, 2, 0]]
gathered_pixels = tf.gather_nd(tensor_h, indices=indices_nd)
print("Gathered pixels:", gathered_pixels)

First image shape: (100, 100, 3)
Every second image shape: (2, 100, 100, 3)
Last element slice shape: (3, 100, 100, 3)
Pixel value at [20, 40] in the second channel of the first image: tf.Tensor(0.952702, shape=(), dtype=float32)
Gathered images shape: (3, 100, 100, 3)
tf.Tensor(
[[[[ 1.1074756e-01 -5.3539753e-01  9.5360279e-01]
   [-8.5091203e-01  3.1157818e-01  1.9795393e+00]
   [-9.6536380e-01 -9.9498802e-01 -1.0608808e+00]
   ...
   [-2.7937093e-01  8.0652155e-02  5.7369366e-02]
   [-7.9319942e-01 -3.7579921e-01 -2.4687603e-02]
   [ 3.8767326e-01 -7.9481333e-01 -4.1359967e-01]]

  [[ 1.1111941e+00  1.2076136e+00  8.5639697e-01]
   [ 4.6293521e-01  1.3895762e+00 -1.5939863e+00]
   [-1.4186718e-01  3.8107908e-01 -2.5388095e-01]
   ...
   [-2.2113810e+00  1.1662598e+00  5.1263064e-01]
   [ 4.8655429e-01  1.2095093e+00  1.5362972e-01]
   [-6.2531716e-01  5.8834648e-01 -1.8336650e+00]]

  [[ 5.4757249e-01  8.1101054e-01 -4.7356081e-01]
   [ 2.9309797e-01 -2.7180332e-01 -4.8951837e-01]
 

In [11]:
# Create a constant tensor
const_d_1 = tf.constant([[1, 2, 3, 4]], shape=[2, 2], dtype=tf.float32)

# Display tensor dimensions
print("Shape using .shape:", const_d_1.shape)
print("Shape using .get_shape():", const_d_1.get_shape())
print("Shape using tf.shape():", tf.shape(const_d_1).numpy())

# Reshape the tensor
reshape_1 = tf.constant([[1, 2, 3], [4, 5, 6]])
reshaped_tensor = tf.reshape(reshape_1, (3, 2))
print("Reshaped tensor:", reshaped_tensor.numpy())

# Expand dimensions
expand_sample_1 = tf.random.normal([100, 100, 3], seed=1)
print("Original data size:", expand_sample_1.shape)
expanded_tensor_axis0 = tf.expand_dims(expand_sample_1, axis=0)
print("Expanded tensor (axis=0):", expanded_tensor_axis0.shape)
expanded_tensor_axis1 = tf.expand_dims(expand_sample_1, axis=1)
print("Expanded tensor (axis=1):", expanded_tensor_axis1.shape)
expanded_tensor_axis_neg1 = tf.expand_dims(expand_sample_1, axis=-1)
print("Expanded tensor (axis=-1):", expanded_tensor_axis_neg1.shape)

# Squeeze dimensions
orig_sample_1 = tf.random.normal([1, 100, 100, 3])
print("Original data size:", orig_sample_1.shape)
squeezed_sample_1 = tf.squeeze(orig_sample_1)
print("Squeezed data size:", squeezed_sample_1.shape)

# Transpose the tensor
trans_sample_1 = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])
print("Original data size:", trans_sample_1.shape)
transposed_sample_1 = tf.transpose(trans_sample_1)
print("Transposed data size:", transposed_sample_1.shape)

# Broadcast the tensor
broadcast_sample_1 = tf.constant([1, 2, 3, 4, 5, 6])
print("Original data:", broadcast_sample_1.numpy())
broadcasted_sample_1 = tf.broadcast_to(broadcast_sample_1, shape=[4, 6])
print("Broadcasted data:", broadcasted_sample_1.numpy())

Shape using .shape: (2, 2)
Shape using .get_shape(): (2, 2)
Shape using tf.shape(): [2 2]
Reshaped tensor: [[1 2]
 [3 4]
 [5 6]]
Original data size: (100, 100, 3)
Expanded tensor (axis=0): (1, 100, 100, 3)
Expanded tensor (axis=1): (100, 1, 100, 3)
Expanded tensor (axis=-1): (100, 100, 3, 1)
Original data size: (1, 100, 100, 3)
Squeezed data size: (100, 100, 3)
Original data size: (2, 3)
Transposed data size: (3, 2)
Original data: [1 2 3 4 5 6]
Broadcasted data: [[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]


In [12]:
import tensorflow as tf

# Arithmetic operations
a = tf.constant([[3, 5], [4, 8]])
b = tf.constant([[1, 6], [2, 9]])
print("Addition:", tf.add(a, b).numpy())
print("Matrix multiplication:", tf.matmul(a, b).numpy())

# Tensor statistics
argmax_sample_1 = tf.constant([[1, 3, 2], [2, 5, 8], [7, 5, 9]])
print("Input tensor:", argmax_sample_1.numpy())
max_sample_1 = tf.argmax(argmax_sample_1, axis=0)
max_sample_2 = tf.argmax(argmax_sample_1, axis=1)
print("Locate the maximum value by column:", max_sample_1.numpy())
print("Locate the maximum value by row:", max_sample_2.numpy())

# Reduce operations
reduce_sample_1 = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])
print("Original data:", reduce_sample_1.numpy())
print("Sum of all elements:", tf.reduce_sum(reduce_sample_1, axis=None).numpy())
print("Sum of each column:", tf.reduce_sum(reduce_sample_1, axis=0).numpy())
print("Sum of each row:", tf.reduce_sum(reduce_sample_1, axis=1).numpy())

Addition: [[ 4 11]
 [ 6 17]]
Matrix multiplication: [[13 63]
 [20 96]]
Input tensor: [[1 3 2]
 [2 5 8]
 [7 5 9]]
Locate the maximum value by column: [2 1 2]
Locate the maximum value by row: [1 2 2]
Original data: [[1 2 3]
 [4 5 6]]
Sum of all elements: 21
Sum of each column: [5 7 9]
Sum of each row: [ 6 15]


In [13]:
import tensorflow as tf
import numpy as np

# Tensor concatenation
concat_sample_1 = tf.random.normal([4, 100, 100, 3])
concat_sample_2 = tf.random.normal([40, 100, 100, 3])
print("Original data size:", concat_sample_1.shape, concat_sample_2.shape)
concated_sample_1 = tf.concat([concat_sample_1, concat_sample_2], axis=0)
print("Concatenated data size:", concated_sample_1.shape)

# Tensor stacking
stack_sample_1 = tf.random.normal([100, 100, 3])
stack_sample_2 = tf.random.normal([100, 100, 3])
print("Original data size:", stack_sample_1.shape, stack_sample_2.shape)
stacked_sample_1 = tf.stack([stack_sample_1, stack_sample_2], axis=0)
print("Stacked data size:", stacked_sample_1.shape)

# Tensor splitting
split_sample_1 = tf.random.normal([10, 100, 100, 3])
print("Original data size:", split_sample_1.shape)
splited_sample_1 = tf.split(split_sample_1, num_or_size_splits=2, axis=0)
print("If num_or_size_splits is 5, the size of the split data is:", np.shape(splited_sample_1))
splited_sample_2 = tf.split(split_sample_1, num_or_size_splits=[3, 5, 2], axis=0)
print("If num_or_size_splits is [3,5,2], the sizes of the split data are:", np.shape(splited_sample_2[0]), np.shape(splited_sample_2[1]), np.shape(splited_sample_2[2]))

Original data size: (4, 100, 100, 3) (40, 100, 100, 3)
Concatenated data size: (44, 100, 100, 3)
Original data size: (100, 100, 3) (100, 100, 3)
Stacked data size: (2, 100, 100, 3)
Original data size: (10, 100, 100, 3)
If num_or_size_splits is 5, the size of the split data is: (2, 5, 100, 100, 3)
If num_or_size_splits is [3,5,2], the sizes of the split data are: (3, 100, 100, 3) (5, 100, 100, 3) (2, 100, 100, 3)


In [14]:
import tensorflow as tf

# Tensor sorting
sort_sample_1 = tf.random.shuffle(tf.range(10))
print("Input tensor:", sort_sample_1.numpy())
sorted_sample_1 = tf.sort(sort_sample_1, direction="ASCENDING")
print("Tensor sorted in ascending order:", sorted_sample_1.numpy())
sorted_sample_2 = tf.argsort(sort_sample_1, direction="ASCENDING")
print("Index of elements in ascending order:", sorted_sample_2.numpy())

# Top-k values
values, index = tf.nn.top_k(sort_sample_1, 5)
print("Input tensor:", sort_sample_1.numpy())
print("k largest values in ascending order:", values.numpy())
print("Indices of the k largest values in ascending order:", index.numpy())

Input tensor: [0 2 3 6 9 4 1 5 7 8]
Tensor sorted in ascending order: [0 1 2 3 4 5 6 7 8 9]
Index of elements in ascending order: [0 6 1 2 5 7 3 8 9 4]
Input tensor: [0 2 3 6 9 4 1 5 7 8]
k largest values in ascending order: [9 8 7 6 5]
Indices of the k largest values in ascending order: [4 9 8 3 7]


In [15]:
import tensorflow as tf

# Eager execution mode
x = tf.ones([2, 2], dtype=tf.dtypes.float32)
y = tf.constant([[1, 2], [3, 4]], dtype=tf.dtypes.float32)
z = tf.matmul(x, y)
print("Eager execution result:", z.numpy())

# Graph mode (using TensorFlow 1.x syntax)
import tensorflow.compat.v1 as tf
tf.disable_eager_execution()
a = tf.ones([2, 2], dtype=tf.dtypes.float32)
b = tf.constant([[1, 2], [3, 4]], dtype=tf.dtypes.float32)
c = tf.matmul(a, b)
with tf.Session() as sess:
    print("Graph mode result:", sess.run(c))

Eager execution result: [[4. 6.]
 [4. 6.]]
Graph mode result: [[4. 6.]
 [4. 6.]]


In [25]:
import tensorflow as tf
import numpy as np

# Autograph example
@tf.function
def simple_nn_layer(w, x, b):
    tf.print(b)
    result = tf.nn.relu(tf.matmul(w, x) + b)
    tf.print("Result:", result)
    return result

w = tf.random.uniform([3, 3])
x = tf.random.uniform([3, 3])
b = tf.constant(0.5, dtype="float32")
result = simple_nn_layer(w, x, b)